using LiteDB; // For BsonMapper registration later, or custom attributes if needed

using Vogen;

namespace TaskTitan.Core;

// --- Define Vogen Value Objects ---
[ValueObject<int>]
// Optional: Add LiteDB BSON Mapper registration attribute IF you create one
// [BsonMapper(typeof(TaskIdMapper))] // Custom mapper example
public partial struct TaskId
{
    // Optional: Add validation if needed (e.g., must be > 0 if generated by DB)
}

[ValueObject<Guid>]
public partial struct TaskUuid { }

[ValueObject<string>]
public partial class ProjectName
{
    // Example Validation: Disallow empty/whitespace, maybe invalid chars
    private static Validation Validate(string value) =>
        string.IsNullOrWhiteSpace(value) ? Validation.Invalid("Project name cannot be empty.") : Validation.Ok;
}

[ValueObject<string>]
public readonly partial struct TagName
{
    // Example Validation: Disallow spaces, commas etc.
    private static Validation Validate(string value) =>
        value.Any(c => char.IsWhiteSpace(c) || c == ',') ? Validation.Invalid("Tag name cannot contain whitespace or commas.") : Validation.Ok;
}

// [ValueObject<char>]
// public readonly partial struct PriorityLevel
// {
//     private static Validation Validate(char value) =>
//         "HML".Contains(char.ToUpperInvariant(value)) ? Validation.Ok : Validation.Invalid("Priority must be H, M, or L.");

//     private static char NormalizeInput(char input) => char.ToUpperInvariant(input);
//     // Normalize to uppercase
//     public static PriorityLevel From(char? value) => From(value ?? 'M');
// }

[ValueObject<DateTimeOffset>] public readonly partial struct DueDate { }
[ValueObject<DateTimeOffset>] public readonly partial struct WaitDate { }
[ValueObject<DateTimeOffset>] public readonly partial struct ScheduledDate { }
[ValueObject<DateTimeOffset>] public readonly partial struct EntryDate { }
[ValueObject<DateTimeOffset>] public readonly partial struct ModifiedDate { }
[ValueObject<DateTimeOffset>] public readonly partial struct EndDate { }


[ValueObject<string>]
public readonly partial struct TaskDescription
{
    private static Validation Validate(string? value) =>
         string.IsNullOrEmpty(value) ? Validation.Invalid("Description cannot be empty.") : Validation.Ok;
}

// --- Define the Task Domain Object ---
// Place this in your Core/Domain layer
public record TaskItem // Changed name slightly to avoid conflict with System.Threading.Tasks.Task
(
    [property: BsonId] // LiteDB specific: Marks this as the document ID
    TaskUuid Uuid, // Use Guid directly or TaskUuid
                   // TaskId? Id, // Typically not set manually on Add, might be auto-incremented by DB or sequence
    TaskDescription Description,
    ProjectName? Project,
    EntryDate Entry,
    ModifiedDate? Modified,
    EndDate? End,
    DueDate? Due,
    WaitDate? Wait,
    TaskItemStatus Status, // Assuming TaskStatus is an enum
                           // PriorityLevel? Priority,
    List<TagName> Tags,
    // List<Annotation> Annotations, // Assuming Annotation is another record/class
    ScheduledDate? Scheduled
// Recurrence? Recurrence,
// List<TaskUuid> Dependencies, // Store Guids for dependencies
// Dictionary<string, object> Udas // UDAs remain tricky for Vogen directly
)
{
    // Default constructor for LiteDB BSON mapping if needed (often required if using classes)
    // Records often work without it if all constructor params match properties.
    // public TaskItem() : this(default, default, default, default, default, default, default, default, default, default, default, default, default) { }
    internal static TaskItem Create(TaskDescription taskDescription, ProjectName? projectName, TaskItemStatus pending, List<TagName> tagVos, DueDate? dueDateVo, EntryDate? entry = null,
    ModifiedDate? modified = null,
    EndDate? end = null,
    DueDate? due = null,
    WaitDate? wait = null)
    {
        throw new NotImplementedException();
    }
}

public enum TaskItemStatus
{
    Pending, Completed, Deleted
}