[report.list]
description = "Pending tasks"
filter = "status:pending"
labels = "ID,Active,Age,D,P,Project,Tags,R,Sch,Due,Until,Description,Urg"
sort = "start-,due+,project+,urgency-"
columns = "id,start.age,entry.age,depends.indicator,priority,project,tags,recur.indicator,scheduled.countdown,due,until.remaining,description.count,urgency"
[report.all]
description = "all tasks"
filter = ""
labels = "ID,St,UUID,A,Age,Done,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description"
sort = "entry-"
columns = "id,status.short,uuid.short,start.active,entry.age,end.age,depends.indicator,priority,project.parent,tags.count,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description"
