// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTitan.Data;

#nullable disable

namespace Data.Sqlite
{
    [DbContext(typeof(TaskTitanDbContext))]
    [Migration("20240505213643_AddTaskCreatedAt")]
    partial class AddTaskCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TaskTitan.Core.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "BqlWvjNY",
                            CreatedAt = new DateTime(2024, 5, 5, 21, 36, 42, 619, DateTimeKind.Utc).AddTicks(5544),
                            Description = "Basic task"
                        },
                        new
                        {
                            Id = "sCBNmoJr",
                            CreatedAt = new DateTime(2024, 5, 5, 21, 36, 42, 619, DateTimeKind.Utc).AddTicks(5550),
                            Description = "Wash the dog"
                        },
                        new
                        {
                            Id = "qGjh4lHm",
                            CreatedAt = new DateTime(2024, 5, 5, 21, 36, 42, 619, DateTimeKind.Utc).AddTicks(5555),
                            Description = "Feed the cats"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
